In [2]:
import numpy as np

In [13]:
a = (np.array([1,2]), np.array([3,4]))
print(type(a))
print(a)
print("------------------------")
np.savez_compressed("data", a)
np.savez("data2", a)
b = np.load("data.npz")["arr_0"]
print(type(b))
print(b)

<class 'tuple'>
(array([1, 2]), array([3, 4]))
------------------------
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]


In [12]:
np.savetxt("savetxt.txt",a)
c = np.loadtxt("savetxt.txt")
print(type(c))
print(c)

<class 'numpy.ndarray'>
[[1. 2.]
 [3. 4.]]


In [16]:
d = np.array([(0,-1), (2,3)])
print(d)

[[ 0 -1]
 [ 2  3]]


In [18]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras import Input, Model

!python --version
print("Tensorflow", tf.__version__)
print(tf.config.list_physical_devices())
print("Found GPU at:", tf.test.gpu_device_name())

Python 3.7.9
Tensorflow 2.1.0
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Found GPU at: /device:GPU:0


In [103]:
def make_model(in_shape):
  input_layer = Input(in_shape[1:])
  layer = tf.split(input_layer, [40,80], axis=2)
  mask = tf.sign(tf.reduce_max(tf.abs(input_layer), axis=2, keepdims=True))
  model = Model(input_layer, [layer,mask])
  return model

In [104]:
model = make_model((None,64,120))
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["acc", "ce"])

model.summary()

Model: "model_7"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_10 (InputLayer)           [(None, 64, 120)]    0                                            
__________________________________________________________________________________________________
tf_op_layer_Abs_5 (TensorFlowOp [(None, 64, 120)]    0           input_10[0][0]                   
__________________________________________________________________________________________________
tf_op_layer_Max_5 (TensorFlowOp [(None, 64, 1)]      0           tf_op_layer_Abs_5[0][0]          
__________________________________________________________________________________________________
tf_op_layer_split_8 (TensorFlow [(None, 64, 40), (No 0           input_10[0][0]                   
____________________________________________________________________________________________

In [111]:
l = model.get_layer("tf_op_layer_split_8")
print(l.__class__.__name__)
l.get_input_shape_at?
print(l.output_shape)
print(l.node_def.op)
x = l.outbound_nodes
print(x)
# x.get_type()
s="a"
s.zfill?

TensorFlowOpLayer
[(None, 64, 40), (None, 64, 80)]
SplitV
[]
